/* ==========================================================================
   DARCX — central content file.
   Everything editable lives here: contact details, projects, services,
   technologies and all Arabic / English interface text.
   ========================================================================== */
const DARCX_DATA = {
  /* ---- Contact channels. Empty values are hidden. instagram / telegram / x / tiktok: username without @;
     facebook / linkedin: page name as in the URL; email: full address ---- */
  contact: {
    whatsapp: "972567574848" /* digits only, with country code */,
    phone: "+972567574848",
    email: "",
    instagram: "",
    telegram: "",
    facebook: "",
    linkedin: "",
    x: "",
    tiktok: "",
    /* fill any empty channel (username / handle only) and its icon appears automatically in the footer and contact page */
  },

  /* ---- Technologies shown on the About page ---- */
  stack: ["HTML", "CSS", "JavaScript", "React", "Firebase", "Vite", "Tailwind CSS"],

  /* ---- Projects ----
     link:      the live website URL, e.g. "https://elbalad.com" (the "Visit website" button appears only when it is filled)
     shots:     images of the website / app itself, e.g. ["assets/img/elbalad-1.jpg", "assets/img/elbalad-2.jpg"]
                (files go in public/assets/img/ — they become the big slider on the project page; the first one is also the card cover)
     dashShots: images of the project's dashboard (a second slider appears only when this list is not empty)
     tech:      list of technologies used on that project (section hides if empty)
     kind:      "web" or "system" — picks the style of the generated preview shown while there are no screenshots */
  projects: [
    {
      slug: "elbalad-water",
      kind: "web",
      accent: "#8998A8",
      name: { ar: "البلد للمياه", en: "El Balad Water" },
      cat: { ar: "موقع إلكتروني", en: "Website" },
      short: {
        ar: "موقع تعريفي يقدّم البلد للمياه بهوية واضحة وتجربة تصفح سهلة.",
        en: "A company website that presents El Balad Water with a clear identity and easy browsing.",
      },
      desc: {
        ar: "موقع إلكتروني صُمّم ليعرض نشاط البلد للمياه وخدماتها بأسلوب منظّم واحترافي، ويتيح للعملاء التعرّف على ما تقدّمه الشركة والتواصل معها بسهولة.",
        en: "A website designed to present El Balad Water and its services in an organised, professional way, helping customers understand what the company offers and reach it easily.",
      },
      features: {
        ar: [
          "تصميم متجاوب مع جميع الأجهزة",
          "عرض منظّم للخدمات والمنتجات",
          "وسائل تواصل مباشرة وواضحة",
          "صفحات خفيفة وسريعة التحميل",
        ],
        en: [
          "Responsive design for every device",
          "Organised presentation of services and products",
          "Clear, direct ways to get in touch",
          "Lightweight, fast-loading pages",
        ],
      },
      problem: {
        ar: "كان النشاط بحاجة إلى حضور رقمي احترافي يعرّف العملاء به ويسهّل الوصول إليه.",
        en: "The business needed a professional digital presence that introduces it to customers and makes it easy to reach.",
      },
      solution: {
        ar: "صمّمنا ونفّذنا موقعًا بسيطًا وسريعًا يعرض المعلومات الأساسية بتسلسل واضح، ويعمل بكفاءة على الجوال.",
        en: "We designed and built a simple, fast website that presents the essentials in a clear sequence and performs well on mobile.",
      },
      tech: [],
      link: "",
      shots: ["assets/img/keo-dash.png", "assets/img/ibrahim.jfif"],
      dashShots: ["assets/img/keo-dash.png", "assets/img/ibrahim.jfif"],
    },
    {
      slug: "keo-studio",
      kind: "web",
      accent: "#B49D94",
      name: { ar: "كيو ستوديو", en: "KEO Studio" },
      cat: { ar: "موقع إلكتروني", en: "Website" },
      short: {
        ar: "موقع يعكس هوية KEO Studio ويعرض أعماله بأسلوب أنيق.",
        en: "A website that reflects the identity of KEO Studio and showcases its work elegantly.",
      },
      desc: {
        ar: "موقع إلكتروني لـ KEO Studio يُبرز هوية الاستوديو ويعرض أعماله وخدماته بتصميم أنيق وتصفّح سلس.",
        en: "A website for KEO Studio that highlights the studio's identity and presents its work and services through an elegant design and smooth browsing.",
      },
      features: {
        ar: [
          "تصميم يعكس هوية الاستوديو",
          "عرض منظّم للأعمال والخدمات",
          "تجربة سلسة على الجوال",
          "قنوات تواصل مباشرة مع الاستوديو",
        ],
        en: [
          "A design that reflects the studio's identity",
          "Organised presentation of work and services",
          "A smooth mobile experience",
          "Direct channels to contact the studio",
        ],
      },
      problem: {
        ar: "احتاج الاستوديو إلى موقع يقدّم أعماله بصورة احترافية ويترك انطباعًا قويًا منذ الزيارة الأولى.",
        en: "The studio needed a website that presents its work professionally and makes a strong first impression.",
      },
      solution: {
        ar: "بنينا موقعًا يُبرز الهوية البصرية للاستوديو ويرتّب المحتوى ليصل الزائر إلى ما يبحث عنه بسرعة.",
        en: "We built a site that showcases the studio's visual identity and arranges content so visitors find what they need quickly.",
      },
      tech: [],
      link: "",
      shots: [],
      dashShots: [],
    },
    {
      slug: "pos-system",
      kind: "system",
      accent: "#A7B4A8",
      name: { ar: "نظام نقاط البيع", en: "Business POS System" },
      cat: { ar: "نظام إدارة أعمال", en: "Business system" },
      short: {
        ar: "نظام نقاط بيع لإدارة المبيعات والمنتجات اليومية بكفاءة.",
        en: "A point-of-sale system for managing daily sales and products efficiently.",
      },
      desc: {
        ar: "نظام نقاط بيع للأعمال يساعد على تنظيم عمليات البيع اليومية وإدارة المنتجات من منصة واحدة.",
        en: "A point-of-sale system for businesses that helps organise daily sales and manage products from a single platform.",
      },
      features: {
        ar: [
          "تسجيل عمليات البيع بسرعة",
          "إدارة المنتجات",
          "واجهة مصمّمة للاستخدام اليومي",
          "تنظيم العمليات في مكان واحد",
        ],
        en: [
          "Fast recording of sales",
          "Product management",
          "An interface built for daily use",
          "Operations organised in one place",
        ],
      },
      problem: {
        ar: "إدارة المبيعات والمنتجات بأساليب متفرقة تستهلك الوقت وتزيد احتمال الأخطاء.",
        en: "Managing sales and products through scattered methods takes time and increases the chance of errors.",
      },
      solution: {
        ar: "جمعنا عمليات البيع وإدارة المنتجات في نظام واحد واضح، يسهل على الفريق استخدامه يوميًا.",
        en: "We brought sales and product management into one clear system that the team can use easily every day.",
      },
      tech: [],
      link: "",
      shots: [],
      dashShots: [],
    },
    {
      slug: "studio-management",
      kind: "system",
      accent: "#8E9A88",
      name: { ar: "نظام إدارة الاستوديو", en: "Studio Management System" },
      cat: { ar: "نظام إدارة أعمال", en: "Business system" },
      short: {
        ar: "نظام إدارة يجمع العمل اليومي للاستوديو في لوحة واحدة.",
        en: "A management system that brings a studio's daily work into one dashboard.",
      },
      desc: {
        ar: "نظام إدارة مصمّم لتنظيم العمل اليومي في الاستوديو، يجمع المعلومات المهمة في لوحة تحكم واحدة.",
        en: "A management system designed to organise a studio's daily work, bringing the important information into a single dashboard.",
      },
      features: {
        ar: ["لوحة تحكم واضحة", "تنظيم العمل اليومي", "معلومات مجمّعة في مكان واحد", "واجهة مناسبة للفريق"],
        en: [
          "A clear dashboard",
          "Organised daily work",
          "Information gathered in one place",
          "An interface suited to the team",
        ],
      },
      problem: {
        ar: "تشتّت معلومات العمل بين أدوات وملفات متعددة يصعّب المتابعة والتنظيم.",
        en: "Work information spread across several tools and files makes it harder to follow and organise.",
      },
      solution: {
        ar: "بنينا نظامًا واحدًا بلوحة تحكم تجمع ما يحتاجه الفريق لمتابعة العمل اليومي.",
        en: "We built a single system with a dashboard that gathers what the team needs to follow daily work.",
      },
      tech: [],
      link: "",
      shots: [],
      dashShots: [],
    },
  ],

  /* ---- Services ---- */
  services: [
    {
      id: "websites",
      accent: "#A7B4A8",
      examples: ["elbalad-water", "keo-studio"],
      name: { ar: "المواقع الإلكترونية", en: "Websites" },
      desc: {
        ar: "مواقع إلكترونية حديثة وسريعة تعرض هوية نشاطك بوضوح وتمنح عملاءك تجربة تصفح سلسة على جميع الأجهزة.",
        en: "Modern, fast websites that present your business with clarity and give your customers a smooth experience on every device.",
      },
      points: {
        ar: [
          "تصميم متجاوب للجوال والحاسوب",
          "واجهات بالعربية والإنجليزية بدعم كامل للاتجاهين",
          "وضعان فاتح وداكن متكاملان",
          "صفحات خفيفة وسريعة التحميل",
        ],
        en: [
          "Responsive design for mobile and desktop",
          "Arabic and English with full RTL and LTR support",
          "Integrated light and dark modes",
          "Lightweight, fast-loading pages",
        ],
      },
    },
    {
      id: "dashboards",
      accent: "#8998A8",
      examples: ["pos-system", "studio-management"],
      name: { ar: "لوحات التحكم", en: "Dashboards" },
      desc: {
        ar: "لوحات تحكم تمكّنك من إدارة المحتوى والبيانات بنفسك، بواجهة منظمة توفّر الوقت وتسهّل المتابعة.",
        en: "Dashboards that let you manage your own content and data through an organised interface that saves time and simplifies follow-up.",
      },
      points: {
        ar: [
          "إدارة المحتوى والبيانات بسهولة",
          "عرض واضح للمعلومات والإحصاءات",
          "صلاحيات مخصّصة للمستخدمين",
          "واجهة منظمة للاستخدام اليومي",
        ],
        en: [
          "Effortless content and data management",
          "Clear presentation of information and statistics",
          "Custom permissions for users",
          "An organised interface for daily use",
        ],
      },
    },
    {
      id: "mobile",
      accent: "#B49D94",
      examples: [],
      name: { ar: "تطبيقات الجوال", en: "Mobile applications" },
      desc: {
        ar: "تطبيقات جوال مصمّمة للمس والاستخدام السريع، تخدم عملاءك وفريقك بتجربة متسقة مع هوية نشاطك.",
        en: "Mobile applications designed for touch and quick use, serving your customers and your team with an experience consistent with your brand.",
      },
      points: {
        ar: ["تطبيقات موجّهة للعملاء", "تطبيقات للفرق الداخلية", "واجهات مصمّمة للمس", "تجربة متسقة مع موقعك ونظامك"],
        en: [
          "Customer-facing applications",
          "Applications for internal teams",
          "Interfaces designed for touch",
          "An experience consistent with your website and systems",
        ],
      },
    },
    {
      id: "systems",
      accent: "#8E9A88",
      examples: ["pos-system", "studio-management"],
      name: { ar: "أنظمة إدارة الأعمال", en: "Business management systems" },
      desc: {
        ar: "أنظمة إدارة أعمال مبنية حول طريقة عملك، تنظّم العمليات اليومية من المبيعات إلى متابعة الفريق في منصة واحدة.",
        en: "Business management systems built around the way you work, organising daily operations from sales to team follow-up on a single platform.",
      },
      points: {
        ar: [
          "نقاط البيع وإدارة المنتجات",
          "تنظيم العمل اليومي والمهام",
          "تقارير ومعلومات في مكان واحد",
          "تصميم يناسب طبيعة نشاطك",
        ],
        en: [
          "Point of sale and product management",
          "Organised daily work and tasks",
          "Reports and information in one place",
          "A design that fits the nature of your business",
        ],
      },
    },
  ],

  /* ---- Interface text ---- */
  i18n: {
    ar: {
      brand: "DARCX",
      skip: "تخطي إلى المحتوى",
      nav_home: "الرئيسية",
      nav_projects: "أعمالنا",
      nav_services: "خدماتنا",
      nav_about: "من نحن",
      nav_contact: "تواصل معنا",
      cta: "ابدأ مشروعك",
      menu: "القائمة",
      close: "إغلاق",
      theme: "تبديل المظهر",
      language: "اللغة",
      more: "عرض المشروع",
      visit: "زيارة الموقع",
      d_dash: "لوحة التحكم",
      c_prev: "السابق",
      c_next: "التالي",
      c_goto: "الصورة",
      h_title: "نبني منتجات رقمية تعمل.",
      h_sub: "مواقع وتطبيقات وأنظمة إدارة مبنية حول عملك.",
      h_cta2: "شاهد أعمالنا",
      h_badge: "استوديو برمجيات",
      h_flow: ["أفكار", "كود", "حلول حقيقية"],
      f_tag: "نبني الرقمي معًا.",
      home_services_t: "ما الذي نبنيه",
      home_services_p: "أربع خدمات تغطي حضورك الرقمي والأنظمة التي يقوم عليها عملك.",
      home_projects_t: "أعمال مختارة",
      home_projects_p: "مشاريع نفّذناها من الفكرة حتى الإطلاق.",
      all_projects: "كل الأعمال",
      all_services: "كل الخدمات",
      home_cta_t: "هل لديك فكرة؟",
      home_cta_p: "أخبرنا عن نشاطك وما تحتاجه، وسنقترح عليك الخطوة الأنسب.",
      s_page_t: "خدماتنا",
      s_page_p: "من الموقع التعريفي إلى نظام إدارة العمل اليومي، نبني ما يناسب نشاطك.",
      s_examples: "أمثلة من أعمالنا",
      s_includes: "ما تشمله الخدمة",
      s_ask: "اطلب هذه الخدمة",
      p_page_t: "أعمالنا",
      p_page_p: "المشاريع التي نفذناها. افتح أي مشروع لتعرف تفاصيله.",
      f_all: "الكل",
      f_web: "مواقع إلكترونية",
      f_sys: "أنظمة إدارة أعمال",
      d_overview: "نظرة عامة",
      d_features: "أبرز المزايا",
      d_tech: "التقنيات",
      d_problem: "المشكلة",
      d_solution: "حلّنا",
      d_back: "كل الأعمال",
      d_next: "المشروع التالي",
      d_cta_t: "تريد مشروعًا مشابهًا؟",
      d_cta_p: "تواصل معنا وأخبرنا بما تحتاجه.",
      a_page_t: "من نحن",
      a_page_p:
        "DARCX استوديو برمجيات يصمّم وينفّذ حلولًا رقمية متكاملة للأعمال: مواقع، لوحات تحكم، تطبيقات جوال وأنظمة إدارة.",
      a_story_t: "قصتنا",
      a_story: [
        "DARCX استوديو برمجيات متخصص في تصميم وتطوير المواقع الإلكترونية ولوحات التحكم وتطبيقات الجوال وأنظمة إدارة الأعمال. نحوّل احتياج كل نشاط إلى منتج رقمي واضح وسهل الاستخدام.",
        "نعمل بفريق صغير ليحظى كل مشروع باهتمام مباشر ومتابعة دقيقة، ونصمّم كل واجهة منذ البداية بالعربية والإنجليزية وبالوضعين الفاتح والداكن، لتبقى التجربة متسقة على جميع الأجهزة.",
      ],
      a_values_t: "كيف نفكر",
      a_values: [
        ["الوضوح", "نبني واجهات مباشرة ومفهومة، يصل فيها المستخدم إلى هدفه بأقل عدد من الخطوات."],
        ["الأداء", "نعتني بسرعة التحميل وسلاسة الاستخدام، بدءًا من الجوال ثم سطح المكتب."],
        ["الإتقان", "نهتم بالتفاصيل: الخطوط والمسافات والتناسق، واتجاه الصفحة الصحيح في اللغة العربية."],
      ],
      a_skills_t: "مهاراتنا",
      a_stack_t: "التقنيات التي نستخدمها",
      c_page_t: "تواصل معنا",
      c_page_p: "أخبرنا عن مشروعك وسنعود إليك.",
      c_form_t: "طلب مشروع",
      c_name: "الاسم",
      c_contact: "البريد الإلكتروني أو رقم الجوال",
      c_service: "نوع المشروع",
      c_msg: "تفاصيل المشروع",
      c_other: "غير ذلك",
      c_send: "إرسال الطلب",
      c_methods: "طرق التواصل",
      c_err: "يرجى تعبئة الاسم ووسيلة التواصل وتفاصيل المشروع.",
      c_ok_wa: "تم فتح واتساب وفيه رسالتك جاهزة. اضغط إرسال لتصلنا.",
      c_ok_mail: "تم فتح البريد برسالتك.",
      c_ok_copy: "تم نسخ رسالتك. الصقها في وسيلة التواصل التي تفضلها.",
      c_wa: "واتساب",
      c_call: "اتصال",
      c_ig: "إنستغرام",
      c_mail: "البريد الإلكتروني",
      c_tg: "تلجرام",
      c_none: "استخدم نموذج الطلب وسنعود إليك.",
      f_desc: "استوديو برمجيات يبني مواقع وتطبيقات وأنظمة إدارة مبنية حول عملك.",
      f_nav: "الصفحات",
      f_serv: "الخدمات",
      f_contact: "التواصل",
      f_rights: "© 2026 DARCX. جميع الحقوق محفوظة.",
      nf_t: "الصفحة غير موجودة",
      nf_p: "المشروع الذي تبحث عنه غير متوفر.",
    },
    en: {
      brand: "DARCX",
      skip: "Skip to content",
      nav_home: "Home",
      nav_projects: "Projects",
      nav_services: "Services",
      nav_about: "About",
      nav_contact: "Contact",
      cta: "Start your project",
      menu: "Menu",
      close: "Close",
      theme: "Toggle theme",
      language: "Language",
      more: "View project",
      visit: "Visit website",
      d_dash: "Dashboard",
      c_prev: "Previous",
      c_next: "Next",
      c_goto: "Image",
      h_title: "We build digital products that work.",
      h_sub: "Websites, applications and business systems built around your business.",
      h_cta2: "See our work",
      h_badge: "Software studio",
      h_flow: ["IDEAS", "CODE", "REAL SOLUTIONS"],
      f_tag: "Build Digital Together.",
      home_services_t: "What we build",
      home_services_p: "Four services covering your digital presence and the systems behind your business.",
      home_projects_t: "Selected projects",
      home_projects_p: "Projects delivered from idea through to launch.",
      all_projects: "All projects",
      all_services: "All services",
      home_cta_t: "Have an idea?",
      home_cta_p: "Tell us about your business and what you need, and we'll suggest the right next step.",
      s_page_t: "Services",
      s_page_p: "From a company website to a system that runs your daily work, we build what fits your business.",
      s_examples: "Examples from our work",
      s_includes: "What it includes",
      s_ask: "Request this service",
      p_page_t: "Projects",
      p_page_p: "The projects we've built. Open any project to see the details.",
      f_all: "All",
      f_web: "Websites",
      f_sys: "Business systems",
      d_overview: "Overview",
      d_features: "Main features",
      d_tech: "Technologies",
      d_problem: "The problem",
      d_solution: "Our solution",
      d_back: "All projects",
      d_next: "Next project",
      d_cta_t: "Want something similar?",
      d_cta_p: "Get in touch and tell us what you need.",
      a_page_t: "About DARCX",
      a_page_p:
        "DARCX is a software studio that designs and delivers complete digital solutions for businesses: websites, dashboards, mobile applications and management systems.",
      a_story_t: "Our story",
      a_story: [
        "DARCX is a software studio focused on designing and building websites, dashboards, mobile applications and business management systems. We turn each business's needs into a clear, dependable digital product.",
        "We work as a small team so every project receives direct attention and careful follow-through. Each interface is designed from the start in Arabic and English, in light and dark, so the experience stays consistent on every device.",
      ],
      a_values_t: "How we think",
      a_values: [
        [
          "Clarity",
          "We build direct, understandable interfaces that help users reach their goal in as few steps as possible.",
        ],
        ["Performance", "We care about load speed and smooth interaction, designed for mobile first and then desktop."],
        [
          "Craft",
          "We pay close attention to detail: typography, spacing, consistency and correct right-to-left layout in Arabic.",
        ],
      ],
      a_skills_t: "Skills",
      a_stack_t: "Technologies we use",
      c_page_t: "Contact",
      c_page_p: "Tell us about your project and we'll get back to you.",
      c_form_t: "Project inquiry",
      c_name: "Name",
      c_contact: "Email or phone number",
      c_service: "Project type",
      c_msg: "Project details",
      c_other: "Something else",
      c_send: "Send inquiry",
      c_methods: "Ways to reach us",
      c_err: "Please fill in your name, a way to reach you and the project details.",
      c_ok_wa: "WhatsApp opened with your message ready. Tap send and it reaches us.",
      c_ok_mail: "Your email app opened with your message.",
      c_ok_copy: "Your message was copied. Paste it into the channel you prefer.",
      c_wa: "WhatsApp",
      c_call: "Call",
      c_ig: "Instagram",
      c_mail: "Email",
      c_tg: "Telegram",
      c_none: "Use the inquiry form and we'll get back to you.",
      f_desc: "A software studio building websites, applications and business systems around your business.",
      f_nav: "Pages",
      f_serv: "Services",
      f_contact: "Contact",
      f_rights: "© 2026 DARCX. All rights reserved.",
      nf_t: "Page not found",
      nf_p: "The project you're looking for isn't available.",
    },
  },

  /* ---- Page titles + descriptions (SEO) ---- */
  seo: {
    home: {
      ar: ["DARCX | نبني منتجات رقمية تعمل", "استوديو برمجيات يبني مواقع وتطبيقات وأنظمة إدارة أعمال مبنية حول عملك."],
      en: [
        "DARCX | We build digital products that work",
        "A software studio building websites, applications and business systems around your business.",
      ],
    },
    services: {
      ar: ["خدماتنا | DARCX", "مواقع إلكترونية، لوحات تحكم، تطبيقات جوال وأنظمة إدارة أعمال."],
      en: ["Services | DARCX", "Websites, dashboards, mobile applications and business management systems."],
    },
    projects: {
      ar: ["أعمالنا | DARCX", "مشاريع DARCX: البلد للمياه، كيو ستوديو، نظام نقاط البيع ونظام إدارة الاستوديو."],
      en: [
        "Projects | DARCX",
        "DARCX projects: El Balad Water, KEO Studio, the Business POS System and the Studio Management System.",
      ],
    },
    about: {
      ar: ["من نحن | DARCX", "تعرّف على DARCX ومهاراتها والتقنيات التي تستخدمها."],
      en: ["About | DARCX", "Get to know DARCX, its skills and the technologies it uses."],
    },
    contact: {
      ar: ["تواصل معنا | DARCX", "أرسل طلب مشروعك إلى DARCX."],
      en: ["Contact | DARCX", "Send your project inquiry to DARCX."],
    },
  },
};

export default DARCX_DATA;
